import json
import os
import re

from openai import OpenAI

## System prompt for the Planner Agent
## Describe its role, the expected output format, and the rules it must follow when generating a navigation plan.
## These are fairly similar to the Analyst Agent, but with a focus on creating a plan based on the requirements provided by the Analyst Agent.

MODEL = os.getenv("QWEN_MODEL", "qwen-plus")
BASE_URL = "https://dashscope.aliyuncs.com/compatible-mode/v1"

# Keys the plan JSON must contain, and the only actions allowed in the system.
REQUIRED_KEYS = {"strategy", "decisions", "stop_point"}
VALID_ACTIONS = {"FORWARD", "LEFT", "RIGHT", "STOP"}
MAX_ATTEMPTS = 3

SYSTEM_PROMPT = """You are a navigation planner (the "Planner Agent") for a mobile robot navigation system.

ROLE:
You receive the validated requirements produced by the Analyst Agent and turn them into a concrete navigation plan.

TASK:
Read the requirements JSON provided by the user and return ONE JSON object that describes the navigation plan.

The JSON object must contain EXACTLY these three keys and no others:
- "strategy": (string) a short description of the navigation strategy. It must say that the robot prefers moving toward its goal whenever this can be done safely, and that it never moves into a blocked direction.
- "decisions": (array of strings) the list of decisions the robot can take during navigation. It must contain exactly these four values and no others, in any order: "FORWARD", "LEFT", "RIGHT", "STOP".
- "stop_point": (string) the condition under which the robot must stop, i.e. when no safe direction is available.

RULES AND CONSTRAINTS:
1. The only allowed actions in the whole system are FORWARD, LEFT, RIGHT, STOP. Never introduce any other action.
2. The robot should prefer moving toward its goal whenever this can be done safely.
3. The robot must never move into a blocked direction.
4. If no safe direction is available, the robot must stop.
5. Output valid JSON only. Do not output markdown, code fences, comments or any explanatory text.
"""


## Function to validate the plan generated by the Planner Agent
## It should first check that the parameter it receives is of the correct type. 
# Then, it should validate all the keys and values contained in the above Python data structure of the input parameter.
def validate_plan(data):
    if not isinstance(data, dict):
        raise ValueError(
            "Plan must be a JSON object (dict), got %s."
            % type(data).__name__
        )

    keys = set(data.keys())
    missing = REQUIRED_KEYS - keys
    extra = keys - REQUIRED_KEYS
    if missing:
        raise ValueError("Missing required key(s): %s" % sorted(missing))
    if extra:
        raise ValueError("Unexpected key(s) introduced by the model: %s" % sorted(extra))

    strategy = data["strategy"]
    if not isinstance(strategy, str) or not strategy.strip():
        raise ValueError('"strategy" must be a non-empty string.')

    decisions = data["decisions"]
    if not isinstance(decisions, list) or not decisions:
        raise ValueError('"decisions" must be a non-empty list.')
    if not all(isinstance(decision, str) for decision in decisions):
        raise ValueError('"decisions" must contain only strings.')
    invalid = set(decisions) - VALID_ACTIONS
    if invalid:
        raise ValueError(
            '"decisions" contains invalid action(s): %s. '
            "Only FORWARD, LEFT, RIGHT, STOP are allowed." % sorted(invalid)
        )
    if set(decisions) != VALID_ACTIONS:
        raise ValueError(
            '"decisions" must contain exactly %s, got %s.'
            % (sorted(VALID_ACTIONS), sorted(set(decisions)))
        )

    stop_point = data["stop_point"]
    if not isinstance(stop_point, str) or not stop_point.strip():
        raise ValueError('"stop_point" must be a non-empty string.')

    return data


## Function to run the Planner Agent
## It takes the requirements generated by the Analyst Agent as input, sends them to the Planner Agent. Just like you did with the Analyst Agent.
## Take the response from the Planner Agent (Qwen), parse it and validate it using the validate_plan function, and return the validated plan.
def run_planner(requirement):
    client = get_client()
    last_error = None
    for attempt in range(1, MAX_ATTEMPTS + 1):
        response = client.chat.completions.create(
            model=MODEL,
            response_format={"type": "json_object"},
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": json.dumps(requirement, ensure_ascii=False)},
            ],
            temperature=0.0,
        )
        raw_text = response.choices[0].message.content
        try:
            data = _parse_json(raw_text)
            return validate_plan(data)
        except (json.JSONDecodeError, ValueError) as error:
            last_error = error
            print("[planner_agent] attempt %d failed: %s" % (attempt, error))
    raise RuntimeError(
        "Planner Agent failed to produce a valid plan after %d "
        "attempts. Last error: %s" % (MAX_ATTEMPTS, last_error)
    )


## The helper functions below are the same ones I used in the Analyst Agent
## from the previous project, so both agents behave in the same way.

def _load_env_file():
    env_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), ".env")
    if not os.path.exists(env_path):
        return
    with open(env_path, "r", encoding="utf-8") as handle:
        for line in handle:
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, _, value = line.partition("=")
            value = value.strip().strip('"').strip("'")
            os.environ.setdefault(key.strip(), value)


def get_client():
    _load_env_file()
    api_key = os.getenv("DASHSCOPE_API_KEY")
    if not api_key:
        raise RuntimeError(
            "DASHSCOPE_API_KEY is not set. Configure it before running:\n"
            '  PowerShell : $env:DASHSCOPE_API_KEY = "sk-..."\n'
            '  bash       : export DASHSCOPE_API_KEY="sk-..."\n'
            "or put  DASHSCOPE_API_KEY=sk-...  in a .env file next to this script."
        )
    return OpenAI(api_key=api_key, base_url=BASE_URL)


def _parse_json(text):
    text = text.strip()
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass
    fence = re.search(r"```(?:json)?\s*(.*?)```", text, re.DOTALL | re.IGNORECASE)
    if fence:
        return json.loads(fence.group(1).strip())
    start, end = text.find("{"), text.rfind("}")
    if start != -1 and end != -1 and end > start:
        return json.loads(text[start:end + 1])
    raise ValueError("Model response did not contain a valid JSON object.")
